### ISSUE TITLE
Mistake in configuration for Symfony

### ISSUE THREAD

**Issue by sylvainlg** [korridor/symfony-scaleway-tem-mailer#5]
Hi

I found a error in https://github.com/korridor/symfony-scaleway-tem-mailer#symfony 

```env
MAILER_DSN=scaleway+api://ACCESS_ID:SECRET@api.scaleway.com
```

In think it should be :

```env
MAILER_DSN=scaleway+api://SCW_PROJECT_ID:SCW_SECRET_KEY@api.scaleway.com
```

Thank you for your work

**Comment by korridor** [comment]
@sylvainlg Thanks for your issue. I just updated the README. I'm not convinced that I agree with the statement that this is an error, but it is for sure clearer this way.
