### ISSUE TITLE
Laravel 10 gives me error  : Unsupported mail transport [scaleway-api].

### ISSUE THREAD

**Issue by gabva** [korridor/symfony-scaleway-tem-mailer#7]
Hi
Thank you for your work
I tried it with Laravel 10 : Unsupported mail transport [scaleway-api].
I've add the transport in AppServiceProvider and set the config

Any help would be appreciated :)

**Comment by korridor** [comment]
@gabva This package is no longer necessary since Symfony created their own mailer for Scaleway TEM.

Please use this instead: https://github.com/symfony/scaleway-mailer
